-- I am a script to drop the data base

/* We can't use this with always data.
DROP DATABASE "M1PAI";
*/

DROP TABLE NEEDED; --This will also drop the seq.
DROP TABLE PROVIDED;
DROP TABLE ASKFRIEND;
DROP TABLE AREFRIEND;
DROP TABLE PARTICIPATE;
DROP TABLE EVENT;
DROP TABLE APPLIUSER;
DROP TABLE RESSOURCE;
DROP TABLE CATEGORY;